accounts/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = "accounts"

# URLパターンを登録するための変数
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('daily_report/', views.DailyView, name="daily_report"),
    path('detail/<int:pk>/', views.Detail, name="detail"),
    path('delete/<int:pk>/', views.delete_post, name='delete_post'),
    path('edit/<int:pk>/', views.edit, name="edit"),
    path('csv/', views.export_items_csv, name='export_items_csv'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("accounts.urls")) # accounts.urls.pyを読み込むための設定を追加
]


accounts/models.py
"""
これはadminです
"""
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.utils import timezone


class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):

    account_id = models.CharField(
        verbose_name=_("account_id"),
        unique=True,
        max_length=10
    )
    email = models.EmailField(
        verbose_name=_("email"),
        unique=True
    )
    first_name = models.CharField(
        verbose_name=_("first_name"),
        max_length=150,
        null=True,
        blank=False
    )
    last_name = models.CharField(
        verbose_name=_("last_name"),
        max_length=150,
        null=True,
        blank=False
    )
    birth_date = models.DateField(
        verbose_name=_("birth_date"),
        blank=True,
        null=True
    )
    is_superuser = models.BooleanField(
        verbose_name=_("is_superuer"),
        default=False
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id' # ログイン時、ユーザー名の代わりにaccount_idを使用
    REQUIRED_FIELDS = ['email']  # スーパーユーザー作成時にemailも設定する

    def __str__(self):
        return self.account_id


class PostDaily(models.Model):
    title = models.CharField('タイトル', max_length=128)
    days = models.DateField(verbose_name="日付", blank=False, null=False, default=timezone.now)
    description = models.TextField('説明', blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   verbose_name="投稿者",
                                   on_delete=models.CASCADE)
    created_at = models.DateTimeField('投稿日', auto_now_add=True)

    def __str__(self):
        return self.title

accounts/forms.py
"""
これはadminです
"""
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from .models import User
from .models import PostDaily
from django import forms


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
            "email",
            "first_name",
            "last_name",
            "birth_date",
        )


class LoginForm(AuthenticationForm):
    """ログインフォーム

    Args:
        AuthenticationForm (AuthenticationForm): Django デフォルトの認証フォーム
    """
    class Meta:
        model = User


# フォームを追加
class PostDailyForm(forms.ModelForm):
    class Meta:
        model = PostDaily
        fields = ('title', 'days', 'description')
        widgets = {
            'days': forms.NumberInput(attrs={
                "type": "date"
            })
        }

accounts/views.py
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.views import (
    LoginView as BaseLoginView,
    LogoutView as BaseLogoutView,
)
from django.urls import reverse_lazy
from .forms import SignUpForm, LoginForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from accounts.models import PostDaily
from .forms import PostDailyForm
from django.http import HttpResponseForbidden
import csv


class IndexView(TemplateView):
    """
    Indexを表示させるための関数
    index.htmlを表示させる
    """
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        """
        DBからPostDailyを取得して
        格納する。

        """
        context = super().get_context_data(**kwargs)
        # ここで必要なデータを取得し、コンテキストに追加する
        postdailies = (
            PostDaily.objects.all()
        )  # 例としてすべての PostDaily インスタンスを取得する
        context["postdailies"] = postdailies
        return context


class SignupView(CreateView):
    """ユーザー登録用ビュー"""

    form_class = SignUpForm  # 作成した登録用フォームを設定
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:index")  # ユーザー作成後のリダイレクト先ページ

    def form_valid(self, form):
        # ユーザー作成後にそのままログイン状態にする設定
        response = super().form_valid(form)
        account_id = form.cleaned_data.get("account_id")
        password = form.cleaned_data.get("password1")
        user = authenticate(account_id=account_id, password=password)
        login(self.request, user)
        return response


# ログインビューを作成
class LoginView(BaseLoginView):
    form_class = LoginForm
    template_name = "accounts/login.html"


# LogoutViewを追加
class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("accounts:index")


def DailyView(request):
    if request.method == "POST":
        form = PostDailyForm(request.POST)
        if form.is_valid():
            days = form.cleaned_data["days"]
            # クエリセットを取得
            exists = PostDaily.objects.filter(days=days, created_by_id=request.user.id).exists()

            # クエリセットの長さを取得
            if not exists:
                postdaily = PostDaily()
                postdaily.days = form.cleaned_data["days"]
                postdaily.title = form.cleaned_data["title"]
                postdaily.description = form.cleaned_data["description"]
                postdaily.created_by = request.user
                postdaily.save()
                return redirect("/")
            else:
                # フォームにエラーメッセージを追加
                form.add_error(None, "指定された日付はすでに存在します。")
        return render(request, "daily_report.html", {"form": form})      
    form = PostDailyForm()
    return render(request, "daily_report.html", {"form": form})


# 各詳細画面
def Detail(request, pk):
    instance = get_object_or_404(PostDaily, pk=pk)
    return render(request, "detail.html", {"instance": instance})


# 削除画面
def delete_post(request, pk):
    instance = get_object_or_404(PostDaily, pk=pk)
    instance.delete()
    return redirect("/")  # 削除後は適切なリダイレクト先を設定する


# 編集画面
def edit(request, pk):
    instance = get_object_or_404(PostDaily, pk=pk)
    if instance.created_by_id != request.user.id:
        return HttpResponseForbidden("このユーザでは許可されていません")
    if request.method == "POST":
        form = PostDailyForm(request.POST, instance=instance)
        if form.is_valid():
            instance.days = form.cleaned_data["days"]
            instance.title = form.cleaned_data["title"]
            instance.description = form.cleaned_data["description"]
            instance.created_by = request.user
            instance.save()
            return redirect("/")
    else:
        form = PostDailyForm(instance=instance)
        return render(request, "edit.html", {"form": form})


# csv出力
def export_items_csv(request):
    # HTTPレスポンスをCSVファイルとして設定
    response = HttpResponse(content_type='/csv')
    response['Content-Disposition'] = 'attachment; filename="items.csv"'

    writer = csv.writer(response)
    writer.writerow(['title'])  # ヘッダー行

    # データ行
    items = PostDaily.objects.all()
    for item in items:
        writer.writerow([item.description])

    return response


# def export_items_csv(request):
#    return HttpResponse("a")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap5のCDNを設定 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <title>Account</title>
</head>

<body>
  <div class="container mx-auto text-center">
    {% block title %}
    {% endblock %}
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

accounts/templates/daily_report.html
{% extends 'base.html' %}

{% block title %}
<div class="h1">daily report</div>
<div class="h1">投稿</div>
{% endblock %}

{% block content %}
<div>
  <div>
    <br>
    投稿内容の表示部分
    <th>タイトル</th>
    <th>{{ instance.title }}</th>

    <form class="" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" name="submit">Submit</button>
    </form>
  </div>
  <div class="mt-3">
    <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
  </div>
</div>
{% endblock %}

accounts/templates/detail.html
{% extends 'base.html' %}
{% block title %}
<div class="h1">詳細画面</div>
{% endblock %}

{% block content %}
<div>
  <div>
    <br>
    <!-- 投稿内容の表示部分 -->
    <table>
      <tr>
        <th>タイトル</th>
        <td>{{ instance.title }}</td>
      </tr>
      <tr>
        <th>投稿日</th>
        <td>{{ instance.created_at }}</td>
      </tr>
      <tr>
        <th>投稿者</th>
        <td>{{ instance.created_by }}</td>
      </tr>
      <tr>
        <th>内容</th>
        <td>{{ instance.description }}</td>
      </tr>
    </table>
  </div>
  <form action="{% url 'accounts:delete_post' pk=instance.pk %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger mt-3">削除</button>
  </form>
  <br>
  <form action="{% url 'accounts:edit' pk=instance.pk %}" method="GET">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger mt-4">変更</button>
  </form>
  <br>
  <br>
  <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
</div>
{% endblock %}

accounts/templates/edit.html
{% extends 'base.html' %}
{% block title %}
<div class="h1">編集画面</div>
{% endblock %}

{% block content %}
<div>
  <div>
    <form class="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" name="submit">Submit</button>
    </form>
    <br>
  </div>
  <!-- 投稿内容の表示部分 -->
  <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
</div>
{% endblock %}

accounts/templates/index.html
{% extends 'base.html' %}

{% block title %}
{% if user.is_authenticated %}
<div class="h1">日報</div>
{% else %}
<div class="h1">Main</div>
{% endif %}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="h2">Welcome {{ user.first_name }} {{ user.last_name }}</div>
<p>日報内容</p>
<!-- 日報一覧の表示 -->
{% for postdaily in postdailies %}
<a href="{% url 'accounts:detail' pk=postdaily.pk %}">{{ postdaily.title }}</a>
<br>
{% endfor %}

<br>
<a href="{% url 'accounts:daily_report' %}" class="btn btn-primary">日報の入力</a>
<br>
<br>
<form action="{% url 'accounts:export_items_csv' %}" method='post'>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">CSV</button>
</form>

<!-- ログアウトフォーム -->
<form action="{% url 'accounts:logout' %}" method='post' name='logout'>
    {% csrf_token %}
    <button type="submit" class="btn btn-link">Logout</button>
</form>
{% else %}
<a href="{% url 'accounts:signup' %}" class="btn btn-primary">Signup</a>
<a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
{% endif %}
{% endblock %}